### ISSUE TITLE
depayco error

### ISSUE THREAD

**Issue by valentinc94** [ma1onso/depayco#1]
No se pudo procesar su pago, verifique que la información ingresada sea correcta. intente desplegar la opcion pero me sale ese error

**Comment by ma1onso** [comment]
Me podrías dar más detalles del error, quizás mostrarme algo de lo que llevas implementado y compartirme el log de error completo. ¿Tienes configuradas las Keys de Epayco en tú proyecto Django?

**Comment by valentinc94** [comment]
Si osea las keys al principio daban error porque pedian string asi que las tuve que definir varias veces el modelo es exactamente el que tienes. la diferencia es que cambie el user por un tipo de user que yo cree. ya te muestro pantallazo

**Comment by valentinc94** [comment]
podrías darme tu numero para contactarte me seria de mucha ayuda aca no puedo postear los pantallazos

**Comment by valentinc94** [comment]
en la setting 

EPAYCO_PUBLIC_KEY = "MY PUBLIC KEY"

EPAYCO_PUBLIC_KEY = 'EPAYCO_PUBLIC_KEY'

EPAYCO_SECRET_KEY: "MI SECRET KEY"

EPAYCO_SECRET_KEY = 'EPAYCO_SECRET_KEY'

DEBUG_EPAYCO = True

DEBUG_EPAYCO = 'DEBUG_EPAYCO'

PLANS = (
    {
        'id_plan': 'love2d_course',
        'name': 'love2d Course',
        'description': 'Hv Premium',
        'amount': 29.99,
        'currency': 'USD',
        'interval': 'month',
        'interval_count': 1,
        'trial_days': 14,
    },
    {
        'id_plan': 'defold_course',
        'name': 'defold Course',
        'description': 'The most mad defold course',
        'amount': 29.99,
        'currency': 'USD',
        'interval': 'month',
        'interval_count': 1,
        'trial_days': 14,
    }
)

**Comment by ma1onso** [comment]
> podrías darme tu numero para contactarte me seria de mucha ayuda aca no puedo postear los pantallazos

Hola, si puedes postear los pantallazos, adjuntalos en un comentario. Por tú segundo comentario veo que no tienes configurado de manera correcta los Keys de Epayco, así no te va a funcionar.

**Comment by valentinc94** [comment]
![Captura de Pantalla 2019-12-10 a la(s) 3 09 54 p  m](https://user-images.githubusercontent.com/52929539/70573079-2c7e0e80-1b6f-11ea-81a3-9289df073979.png)
![Captura de Pantalla 2019-12-10 a la(s) 3 10 14 p  m](https://user-images.githubusercontent.com/52929539/70573080-2d16a500-1b6f-11ea-901c-becd72e16a3c.png)

**Comment by valentinc94** [comment]
![Captura de Pantalla 2019-12-10 a la(s) 5 05 37 p  m](https://user-images.githubusercontent.com/52929539/70573147-520b1800-1b6f-11ea-947d-c6faad8173d6.png)

**Comment by valentinc94** [comment]
![Captura de Pantalla 2019-12-10 a la(s) 5 13 03 p  m](https://user-images.githubusercontent.com/52929539/70573629-5ab01e00-1b70-11ea-8f26-b275f15c9e33.png)

**Comment by ma1onso** [comment]
Elimina las líneas 296, 300 y 304 de tu settings.py. Como lo tienes ahora, se están sobreescribiendo los valores que deberías dejar con los valores que yo puse en el README.

**Comment by valentinc94** [comment]
No se pudo procesar su pago, verifique que la información ingresada sea correcta aun me sale eso y elimine las lineas que me dijiste

**Comment by valentinc94** [comment]
![Captura de Pantalla 2019-12-11 a la(s) 8 31 51 a  m](https://user-images.githubusercontent.com/52929539/70625592-b5895a00-1bf0-11ea-9726-0b93e5e52e9d.png)

**Comment by valentinc94** [comment]
tambien cuando intento entrar a la url de subscripcion Dx y le doy comprar membrecia me sale everse for 'my_subscription' not found. 'my_subscription' is not a valid view function or pattern name. y tampoco consigo la url xDD esa

**Comment by ma1onso** [comment]
Al parecer el problema es más porque no estas configurando correctamente mi paquete dentro de tu proyecto. En este caso debes tratar de entender primero como funciona Django, para poder usar este proyecto. ¿Ya instalaste depayco en settings.py? ¿ya corriste las migraciones?

**Comment by valentinc94** [comment]
'depayco', ya esta en apps instaladas pues migraciones las borros y las corro again (?)

**Comment by ma1onso** [comment]
Si no tienes problema en pasarme tú proyecto, podría revisar que esta mal e intentar ayudarte con la integración. Porque realmente no se que pueda estar mal, adicional a lo que ya corregiste.

**Comment by valentinc94** [comment]
en mi caso no uso abstract request.session['mark'] == 0 y request.session['mark'] == 1 asi los diferencios como seria en la caso de los addons para esta parte :?

**Comment by valentinc94** [comment]
yo tengo la siguiente tabla 
![Captura de Pantalla 2019-12-11 a la(s) 10 25 28 a  m](https://user-images.githubusercontent.com/52929539/70634660-9abee180-1c00-11ea-88e8-4d342634c248.png)

creo que la razon es porque como yo no uso abstrac user en esta parte es que se presenta 
![Captura de Pantalla 2019-12-11 a la(s) 10 26 12 a  m](https://user-images.githubusercontent.com/52929539/70634681-ad391b00-1c00-11ea-942f-823c7cc03cef.png) asi que lo mas probable es que deba adaptarlo pero no xD tengo idea jeje se que son por los metodos decorator pero como yo no quise usar abstracuser 
![Captura de Pantalla 2019-12-11 a la(s) 10 26 39 a  m](https://user-images.githubusercontent.com/52929539/70634738-c17d1800-1c00-11ea-9fa8-4a7ef72af71b.png)

**Comment by ma1onso** [comment]
Si no hay problema, enviame tú proyecto en un .zip y lo corro en mi local en intento dar con el error.

**Comment by valentinc94** [comment]
Por asuntos de confidencialidad no puedo. Hice algunos pasos de los que te habia mensionado y ya me crea la tabla customer la cuestion es que cuando le doy guardar me sale. ahora

KeyError at /depaycoprocess-payment/
'current_period_start'


y ahora me sale XD 
ErrorException at /depaycoprocess-payment/
ErrorException:{[101] Error de comunicación con el servicio}

ALGUN consejo?

**Comment by ma1onso** [comment]
Listo entiendo, tenía la idea de que podía ser un proyecto personal. Realmente entiendo donde esta fallando tú aplicación, pero actualmente no tengo instalado en mi computador el proyecto donde use esta aplicación. Hagamos lo siguiente, crea un nuevo proyecto en Django, instala esta aplicación, configura lo que indico en el REAMDE y prueba. Si te sale el mismo error, me compartes el proyecto, como es un proyecto de prueba, no tendrás problema en compartirlo. Quedo atento para seguir asistiendote.

**Comment by valentinc94** [comment]
xD es que no uso abstrac user me tomara un momento mientras explicare.

asi que en la view hice el siguiente cambio

class ProcessPayment(View):
    def post(self, request):
        try:
            mark = int(request.session['mark'])
        except:
            mark = None
        if mark == 0:        
            u_id = request.session.get('id')
            cand = Candidatos.objects.get(id=u_id)

            token = credit_cards.tokenize(
                credit_card_number=request.POST.get('credit_card_number'),
                exp_year=request.POST.get('credit_card_exp_year'),
                exp_month=request.POST.get('credit_card_exp_month'),
                cvc=request.POST.get('cvc'),
            )['data']['id']

            customer = customers.create(
                credit_card_token=token,
                name=request.POST.get('name'),
                email=request.POST.get('email'),
                phone=request.POST.get('phone'),
                user_id=cand.id,
                identification_type=request.POST.get('identification_type'),
                identification_number=request.POST.get('identification_number'),
            )

            subscriptions.create_and_charge(
                plan_id='hv_premium_1',
                customer_id=customer.id,
                credit_card_token=token,
                identification_type=request.POST.get('identification_type'),
                identification_number=request.POST.get('identification_number'),
            )
        else:
            messages.add_message(
                request,
                messages.WARNING,
                'No se pudo procesar su pago, verifique que la información ingresada sea correcta',
            )
            form = ChargeInformationForm(request.POST)

            return render(
                request, 'epayco-form.html', {
                    'form': form
                }
            )

        return redirect(reverse('home'))
para que me funcionase y poder crear el usuario la cuestion es que creo que como me jala el id y no lo convierte como cuando usas request puede presentar problema primero observe eso. Pero cuando le doy guardar me da error KeyError at /depaycoprocess-payment/
'current_period_start' en settings tengo

PLANS = (
    {
        'id_plan': 'hv_premium_1',
        'name': 'Hv Premium',
        'description': 'Hv Premium',
        'amount': 30000.00,
        'currency': 'Cop',
        'interval': 'month',
        'interval_count': 1,
        'trial_days': 30,
    },
    {
        'id_plan': 'defold_course',
        'name': 'defold Course',
        'description': 'The most mad defold course',
        'amount': 29.99,
        'currency': 'USD',
        'interval': 'month',
        'interval_count': 1,
        'trial_days': 14,
    }
)

no se a que se deba. Como dije no uso abstrac user literal cree una tabla llamada candidato y le cree su login etc sin necesidad de usar el abstrac user de django. 

Observando por superadmin puedo crear los objetos sin ningun problema pero cuando le doy guardar no me crea ni el plan ni la suscripcion pero si el costumer

**Comment by ma1onso** [comment]
Hola nuevamente, con eso que me escribes es muy difícil ayudarte, puesto que no puedo rastrear que genera el error con exactitud. Así que puedo esperar sin problema a que me pruebes con un proyecto desde cero y que luego me lo envíes (en caso de que sigas presentando el mismo error). Disculpa cualquier problema que te haya causado mi librería y espero poder ayudarte. (Más adelante espero subirla a pypi.org/ para que la puedan instalar más facilmente : ).

**Comment by valentinc94** [comment]
use un proyecto con abstrac user viejo que tengo y el mismo no me da error en lo absoluto me manda a la view sin problemas el id en costumer si lo encripta como en el tuyo pero no me crea ni plan ni proyecto.

**Comment by valentinc94** [comment]
y en lo absoluto muchas gracias por guiarme con soporte

**Comment by valentinc94** [comment]
y si usamos team viewer? asi puedes ver el problema por completo

**Comment by valentinc94** [comment]
listo hice unos cambios y ya verifique en el dashboard de epayco efectivamente me lo lista como cliente pero me da error KeyError at /depaycoprocess-payment/
'current_period_start'

xD es lo unico ya con eso corono

**Comment by ma1onso** [comment]
> use un proyecto con abstrac user viejo que tengo y el mismo no me da error en lo absoluto me manda a la view sin problemas el id en costumer si lo encripta como en el tuyo pero no me crea ni plan ni proyecto.

Perfecto, entonces quizás la modificación que hiciste en mi librería esta haciendo que falle en tu proyecto. Pasame ese proyecto y yo verifico lo otro que pueda estar sucediendo. No tengo tiempo ahora mismo para asistirte por TeamViewer porque estoy trabajando. Saludos.

**Comment by ma1onso** [comment]
> listo hice unos cambios y ya verifique en el dashboard de epayco efectivamente me lo lista como cliente pero me da error KeyError at /depaycoprocess-payment/
> 'current_period_start'
> 
> xD es lo unico ya con eso corono

¿Este error no te sale en el otro proyecto?

**Comment by valentinc94** [comment]
No pero no crea el plan ni lo busca

**Comment by valentinc94** [comment]
Buenos dias Ma1onso osea imagina que haces el servicio de pago y escribes los datos y le des guardar. La solicitud efectivamente se hace en la plataforma pero obvio da error. Usando /admin y observando la tabla costumer efectivamente se registra pero la tabla plan ni subscripcion lo hacen

**Comment by valentinc94** [comment]
Buenas tardes amigo ya te estoy preparando un demo para que puedas correrlo y verlo

**Comment by valentinc94** [comment]
ya pude resolver por completo. para los usuarios que no usen abstrac user deben hacer la siguiente configuracion en el paquete en decorators agregar lo siguiente

mark = int(request.session['mark'])

        # Buscador de trabajo
        if mark == 0:
            u_id = request.session.get('id')
            cand = Candidatos.objects.get(id=u_id)

dentro de cada request 

sustituyen request.user_autentificate por 

cand: 

y en la view del paquete la linea 36 donde jala el id poner
user_id=request.session.get('id'), 

muchas gracias por esta brillante libreria :)

**Comment by ma1onso** [comment]
> ya pude resolver por completo. para los usuarios que no usen abstrac user deben hacer la siguiente configuracion en el paquete en decorators agregar lo siguiente
> 
> mark = int(request.session['mark'])
> 
> ```
>     # Buscador de trabajo
>     if mark == 0:
>         u_id = request.session.get('id')
>         cand = Candidatos.objects.get(id=u_id)
> ```
> 
> dentro de cada request
> 
> sustituyen request.user_autentificate por
> 
> cand:
> 
> y en la view del paquete la linea 36 donde jala el id poner
> user_id=request.session.get('id'),
> 
> muchas gracias por esta brillante libreria :)

Perfecto, tendré en cuenta como hacer para soportar User fuera del User que viene con el paquete Django.

**Comment by ma1onso** [comment]
@valentinc94 por si lo necesitas más adelante, he subido la librería a pypi para que sea más facil de instalar y para recibir nuevas actualizaciones: https://pypi.org/project/depayco/. En tu caso no te serviría esa versión porque modificaste partes de la librería, pero hay te dejo el dato.
